# Generated by Django 2.2.24 on 2022-10-21 12:54

from django.db import migrations

def get_newbuilding_status(apps, schema_editor):

    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year < 2015:
            flat.new_building = False
        else:
            flat.new_building = True
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20221021_1836'),
    ]

    operations = [migrations.RunPython(get_newbuilding_status),
    ]
