# Generated by Django 2.2.24 on 2022-10-21 19:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_appeal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appeal',
            new_name='Complaint',
        ),
    ]
