# Generated by Django 2.2.24 on 2022-10-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20221022_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(verbose_name='Текст жалобы'),
        ),
    ]
