# Generated by Django 2.2.24 on 2022-10-22 10:34

from django.db import migrations
import phonenumbers

def get_newbuilding_status(apps, schema_editor):

    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parse_number = phonenumbers.parse(flat.owners_phonenumber,  "RU")
        serialized_number = phonenumbers.format_number(parse_number, phonenumbers.PhoneNumberFormat.E164)
        flat.owner_pure_phone = serialized_number
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20221022_1632'),
    ]

    operations = [migrations.RunPython(get_newbuilding_status),
    ]
