# Generated by Django 2.2.24 on 2022-10-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_flats',
            field=models.ManyToManyField(blank=True, null=True, related_name='owner_flats', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
