# Generated by Django 2.2.24 on 2022-10-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20221023_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_flats',
            field=models.ManyToManyField(db_index=True, null=True, related_name='owner_flats', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
