# Generated by Django 2.2.24 on 2022-10-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_auto_20221028_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_flats',
            new_name='flats',
        ),
    ]
