# Generated by Django 2.2.24 on 2022-11-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_auto_20221102_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='full_name',
        ),
    ]
